import { LorebookEntry, Lorebook } from "@/types/lorebook"

export const ENTRY_DEFAULTS: LorebookEntry = {
  uid: 0,
  key: [],
  keysecondary: [],
  comment: "",
  content: "",
  constant: false,
  vectorized: false,
  selective: true,
  selectiveLogic: 0,
  addMemo: true,
  order: 100,
  position: 0,
  disable: false,
  ignoreBudget: false,
  excludeRecursion: false,
  preventRecursion: false,
  matchPersonaDescription: false,
  matchCharacterDescription: false,
  matchCharacterPersonality: false,
  matchCharacterDepthPrompt: false,
  matchScenario: false,
  matchCreatorNotes: false,
  delayUntilRecursion: false,
  probability: 100,
  useProbability: true,
  depth: 4,
  outletName: "",
  group: "",
  groupOverride: false,
  groupWeight: 100,
  scanDepth: null,
  caseSensitive: null,
  matchWholeWords: null,
  useGroupScoring: null,
  automationId: "",
  role: null,
  sticky: 0,
  cooldown: 0,
  delay: 0,
  triggers: [],
  displayIndex: 0,
}

export const LOREBOOK_DEFAULTS: Omit<Lorebook, "entries"> = {
  name: "Untitled Lorebook",
  description: "",
  scanDepth: 4,
  tokenBudget: 512,
  recursiveScanning: true,
  extensions: {},
}